name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print working directory and files
        run: |
          pwd
          ls -al

      - name: Deploy files via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: 3.133.152.101
          username: ubuntu
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAgEArzN3je4tCC5yb8DIA0IZYHP5gGFkA3xIylr69nFYnyrA51AieE/p
            xcfFXijwXtNfTtKKYPsoFehEATCtdzrWyl1IDQMP6eUHU2OSom53ohq9Jd3pgMjrZFg2r+
            rqdsahQJIuU0S3bECnXgley49CKokTtO6nO++WiB+XmTJW3YIsp8PPJETkDqD82XctRBbG
            rR9YWdSWULByG2c0co3vuweoDtjcyVlrlm0FHARo8sR6zaAwGb41iHosnhKqQSjWlkQbbd
            9+KteQtvPStzCTnqGSVayeov59c4n6f8/3dhWVCCnYPR0vfQ5ixzZnWJqcTOYAd9zcluZs
            LoEHIEnbBeaa757o1Tar7VoBjen0rs7NwiQkGIlL7kTLeyjnzufRZ18St4hWo+GHsgu/ej
            NRteqenKsnHjepiSbK7CqQ2tsY8BcFfPxaPkvrw3PPx5brft/TEhC/HzXp6m02xoUU54SR
            q6GOornTg/YXZiNIQFl66RYIe5U2/9f+DQkV+VXSx9k0/PBtHvgz1f76kDMX/7eN7NzUmH
            Op2vBMSUvNGJ6wm+N4gTV63fcSBsSb5A2gyIf95gALjo4nheGWHC2AE625aFGsNmdphf8S
            kPZj4li4dpsNW6tXqaxOZupEVYgA90psXsAnj5xzkVxzuzoWXP9F0BaK2DFJW10EVt1wc1
            sAAAdIiOvIGojryBoAAAAHc3NoLXJzYQAAAgEArzN3je4tCC5yb8DIA0IZYHP5gGFkA3xI
            ylr69nFYnyrA51AieE/pxcfFXijwXtNfTtKKYPsoFehEATCtdzrWyl1IDQMP6eUHU2OSom
            53ohq9Jd3pgMjrZFg2r+rqdsahQJIuU0S3bECnXgley49CKokTtO6nO++WiB+XmTJW3YIs
            p8PPJETkDqD82XctRBbGrR9YWdSWULByG2c0co3vuweoDtjcyVlrlm0FHARo8sR6zaAwGb
            41iHosnhKqQSjWlkQbbd9+KteQtvPStzCTnqGSVayeov59c4n6f8/3dhWVCCnYPR0vfQ5i
            xzZnWJqcTOYAd9zcluZsLoEHIEnbBeaa757o1Tar7VoBjen0rs7NwiQkGIlL7kTLeyjnzu
            fRZ18St4hWo+GHsgu/ejNRteqenKsnHjepiSbK7CqQ2tsY8BcFfPxaPkvrw3PPx5brft/T
            EhC/HzXp6m02xoUU54SRq6GOornTg/YXZiNIQFl66RYIe5U2/9f+DQkV+VXSx9k0/PBtHv
            gz1f76kDMX/7eN7NzUmHOp2vBMSUvNGJ6wm+N4gTV63fcSBsSb5A2gyIf95gALjo4nheGW
            HC2AE625aFGsNmdphf8SkPZj4li4dpsNW6tXqaxOZupEVYgA90psXsAnj5xzkVxzuzoWXP
            9F0BaK2DFJW10EVt1wc1sAAAADAQABAAACAACbWgeo0okbuBPBBDBWs0XNQQj7zV/ht1LU
            G9hsrhTnDgH/Gg92n2Wq+nkIBUUe0E6ylf4eAJaK1ml2pLMsBgBvcEdzQkPaIjtcte5QGa
            P7Gbqe2Sc0CvSvBYl4c9VzfK1/lB9/tm7ujmXZ/HUSCvWgweu3g+bGPqw8B8dlED32LHds
            SzRh9LRERHvwWLzKo2eIG0M8ZETlR4/mvJzE9xabwS5D/AfKgn/j4selEEP/ADnkGyaLrR
            3K5oqpn+NX495jYADybDpzwrGPiKRPy8MZ5irbzTTdUsvqp2535vCGxJxhoLkdd8OkIB12
            h8cbyfzOMyQ3JKB1Ldy/X6nx94s9OEXG/eaMzXq8wT5vHRCiUWTjr9bRrmtAym8sSEPyUO
            MHIMtk4OeKPaOBEbFe0ptudAp6uIj0plyl9fmkoYXTFckjUsindVmxSGtWJqnhxH5Z2/NS
            owijHUVfb2NWJKX71HXDdki5Z6L7KHlEUWOU7MgzQwEBa4SbUYZ24aSGXOcnHwrGUMh/TV
            fjcMW3x3C/VJuniUAz+lz5MEm3DmmBD6hJ+Sq75PevSieFv1Yd/bX8FNAepaAVbbDy5oNI
            Mf9BI+OJYY9qzzDoqJw9vfEMxii79sUK+vEGFkp7zHzZmeoFEsIEsm70milJefRBGjP7jm
            Rloq4AGbKZejVgN0hxAAABAQDIOZt9p51Hu6REQ4h2AepcyrI4Mtqc31t6Ryuxif2qA0Jb
            aalY0nmPC2GzLT0pO3ZsVbkKr1MwYaxNzk0IoyvLuRqKN7vFAXx0QQqLL6XNTAr/luxPHy
            3EQoc2OyxcITtfXZDx3XCBTqfk/LV87JDo3oSOdFbArhtHlxrWOzbUeGKfzxmkpi5QE5fq
            7z/vZqdLx2irB+W4yN2/DC4A+P97ZIOlh0bKTkTMUFDTJVxgYJTAkbAgeeUVuHDok/uGW9
            lZ/phoIlMsGKUBcxzWkyhySGAnK/5sJES2yEWcQk32s0+2CcwKdUwmon7FhNovxqLQrBVz
            om+hsUCyd0UHm0UUAAABAQDdo5keZtcHkMf9v6+puA+OnwtbRLOhlj5CCZ51IO328AtfMW
            L3aawChSsjM+mtXxszs3yOK1eifrYCJgFBOX5PVd8E1MIDoOHSkXA0e+GoMH456FN7XqLf
            3dz0r0Tn3vXPcgvwP9RdwPREbBvBoszz3WRj2YhGpt4d0kaTxgEsQxSdatO2ewtIj8ieP4
            B2pKBOisrlFe2PjzbpDlVQeqlqNyHFivoRUgOQ+bIpRQ8qYGD/H2O6uIsFG2zheWhuwKzL
            EE26D9bPKMbANFfY6g9UPH96pP1QDj+m6iRiRQXNwdjNaUi7R5k+EFU4m+Lkmnx9pg0M68
            g4AzQpJhOPWyqjAAABAQDKXNbEiUax5GeiMv6NfTBMjlbVlYUF4//YQVbRu1fTvyOYU8W1
            zgwBxMnGfYks4WbFC+f+hJlDnGRCY/RgsjIiMVW9snKFsCtEOOv6iN2NUfzd9vHMPBar3C
            M6xcpRqxZiTBCOSzZ2u0oBOgk07JzFEGhz7T1Cse8pq3TNKAozOol6uVyzHSSBlS0y4BlD
            mkAXacZ1CEQB6jPCJ4GwvzHFxcT3EfI1aZwVFAgHwz+nrLIzY1toknjC0QdqumG/j4dvd9
            jgzjjVl+bi70CctLPC1r147pBCfmn9JHZOg6eXjVyHaZu1bDIZdogbrUtNEuZqpXQQTSWm
            KSuEJ7t+9hfpAAAADmdpdGh1Yi1hY3Rpb25zAQIDBA==
            -----END OPENSSH PRIVATE KEY-----
          port: 22
          source: "index.html,style.css,main.js"
          target: "/var/www/html"
          strip_components: 0
          debug: true
          overwrite: true
