name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print working directory and files
        run: |
          pwd
          ls -al

      - name: Deploy files via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: 3.133.152.101
          username: ubuntu
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn...
            ...(your full private key contents here, exactly as copied from VS Code)...
            -----END OPENSSH PRIVATE KEY-----
          port: 22
          source: "index.html,style.css,main.js"
          target: "/var/www/html"
          strip_components: 0
          debug: true
          overwrite: true
